use super::{quick_fix::RuleQuickFix, rule::RuleAction, severity::RuleSeverity};
use crate::parser::TextRange;

/// Represents a diagnostic action (error, warning, etc.) generated by a rule.
#[derive(Debug, Clone)]
pub struct DiagnosticAction {
    /// The severity of this violation.
    pub severity: RuleSeverity,
    /// The descriptive message detailing the issue.
    pub message: String,
    /// The precise location in the text buffer where the violation occurred.
    pub range: TextRange,
    /// Optional quick fixes that can resolve the issue.
    pub quick_fixes: Vec<RuleQuickFix>,
}

impl DiagnosticAction {
    /// Creates a new diagnostic action.
    pub fn new(severity: RuleSeverity, message: impl Into<String>, range: TextRange) -> Self {
        Self {
            severity,
            message: message.into(),
            range,
            quick_fixes: Vec::new(),
        }
    }

    /// Appends a quick fix to the diagnostic.
    pub fn with_quick_fix(mut self, fix: RuleQuickFix) -> Self {
        self.quick_fixes.push(fix);
        self
    }
}

impl RuleAction for DiagnosticAction {
    fn as_diagnostic(&self) -> Option<&crate::rules::action::DiagnosticAction> {
        Some(self)
    }
}
