use super::{errors::Result, metadata::RuleMetadata};
use std::any::Any;

/// Trait representing the execution context for a rule.
/// This will be fully implemented in phase 14.4.
pub trait RuleContext: Send + Sync {
    fn as_any(&self) -> &dyn Any;
}

/// Trait representing an action generated by a rule (e.g., Diagnostic, QuickFix).
pub trait RuleAction: Send + Sync {
    /// Allows casting the action into a DiagnosticAction if it is one.
    fn as_diagnostic(&self) -> Option<&crate::rules::action::DiagnosticAction> {
        None
    }
}

/// The core trait that all rules in the Universal Rule Engine must implement.
pub trait Rule: Send + Sync {
    /// Returns the metadata describing this rule.
    fn metadata(&self) -> &RuleMetadata;

    /// Evaluates the rule against the given context.
    /// Returns a list of actions (e.g., diagnostics, quick fixes) if the rule is violated.
    fn evaluate(&self, ctx: &dyn RuleContext) -> Result<Vec<Box<dyn RuleAction>>>;
}
