[package]
name = "gic-tui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
gic-core.workspace = true
ratatui.workspace = true
crossterm.workspace = true
tracing.workspace = true
thiserror.workspace = true
unicode-width = "0.2"
tree-sitter-highlight = "0.24.7"
tree-sitter-rust = "0.24.2"
tree-sitter-yaml = "0.7.2"
tree-sitter-json = "0.24.8"
tree-sitter-toml = "0.20.0"
tree-sitter-md = "0.5.3"
tree-sitter-bash = "0.25.1"
tree-sitter-dockerfile = "0.2.0"
tree-sitter-hcl = "1.1.0"
tree-sitter = "0.24.7"
streaming-iterator = "0.1.9"
