//! YAML Core Validation Engine.
//!
//! Evaluates YAML documents against core syntax and semantic rules (indentation,
//! duplicate keys, anchors/aliases, missing colons, unexpected EOF, malformed syntax)
//! and generates structured diagnostics with quick-fix recommendations.

use crate::yaml::aliases::AliasResolver;
use crate::yaml::anchors::AnchorExtractor;
use crate::yaml::duplicate_keys::DuplicateKeyDetector;
use crate::yaml::errors::YamlError;
use crate::yaml::indentation::{IndentationAnalyzer, IndentationIssueKind};
use crate::yaml::parser::{Position, Span, YamlAST, YamlParser};

/// Validation severity levels for YAML diagnostics.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum YamlSeverity {
    Error,
    Warning,
    Info,
    Hint,
}

/// Suggested automated edit to resolve a YAML validation error.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct YamlQuickFix {
    /// Action title displayed to user.
    pub title: String,
    /// Replacement string.
    pub replacement: String,
    /// Target span to replace.
    pub span: Span,
}

/// Structured diagnostic item generated by `YamlValidator`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct YamlValidationDiagnostic {
    /// Unique rule identifier (e.g. `yaml-no-tabs`, `yaml-duplicate-key`).
    pub rule_id: String,
    /// Human-readable problem description.
    pub message: String,
    /// Diagnostic severity.
    pub severity: YamlSeverity,
    /// Exact target span in source text.
    pub span: Span,
    /// Optional automated quick-fix edit.
    pub quick_fix: Option<YamlQuickFix>,
}

/// Configuration options for `YamlValidator`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct YamlValidatorOptions {
    /// Check for tab characters in indentation.
    pub check_indentation: bool,
    /// Check for duplicate keys in mappings.
    pub check_duplicate_keys: bool,
    /// Resolve and validate anchor/alias references.
    pub check_anchors_and_aliases: bool,
    /// Expected indentation step size (default 2).
    pub indent_step: usize,
}

impl Default for YamlValidatorOptions {
    fn default() -> Self {
        Self {
            check_indentation: true,
            check_duplicate_keys: true,
            check_anchors_and_aliases: true,
            indent_step: 2,
        }
    }
}

/// Core YAML Validator coordinating syntax, semantic, and structural checks.
#[derive(Debug, Clone)]
pub struct YamlValidator {
    options: YamlValidatorOptions,
}

impl Default for YamlValidator {
    fn default() -> Self {
        Self::new(YamlValidatorOptions::default())
    }
}

impl YamlValidator {
    /// Constructs a new YamlValidator with specified options.
    pub fn new(options: YamlValidatorOptions) -> Self {
        Self { options }
    }

    /// Validates raw YAML source code and returns all detected diagnostics.
    pub fn validate_source(&self, source: &str) -> Vec<YamlValidationDiagnostic> {
        let mut diagnostics = Vec::new();

        // 1. Indentation Analysis
        if self.options.check_indentation {
            let indent_analyzer = IndentationAnalyzer::new(self.options.indent_step);
            let report = indent_analyzer.analyze(source);

            for issue in report.issues {
                let (rule_id, severity, quick_fix) = match issue.kind {
                    IndentationIssueKind::TabCharacter => (
                        "yaml-no-tabs",
                        YamlSeverity::Error,
                        Some(YamlQuickFix {
                            title: "Convert tabs to spaces".to_string(),
                            replacement: " ".repeat(self.options.indent_step),
                            span: issue.span,
                        }),
                    ),
                    IndentationIssueKind::MixedTabsAndSpaces => (
                        "yaml-mixed-indentation",
                        YamlSeverity::Error,
                        Some(YamlQuickFix {
                            title: "Replace with uniform spaces".to_string(),
                            replacement: " ".repeat(issue.expected),
                            span: issue.span,
                        }),
                    ),
                    IndentationIssueKind::InconsistentStep => (
                        "yaml-indent-step",
                        YamlSeverity::Warning,
                        Some(YamlQuickFix {
                            title: format!("Align to {} space step", self.options.indent_step),
                            replacement: " ".repeat(issue.expected),
                            span: issue.span,
                        }),
                    ),
                    IndentationIssueKind::UnexpectedIndent => {
                        ("yaml-unexpected-indent", YamlSeverity::Error, None)
                    }
                    IndentationIssueKind::TrailingWhitespace => (
                        "yaml-trailing-whitespace",
                        YamlSeverity::Hint,
                        Some(YamlQuickFix {
                            title: "Trim trailing whitespace".to_string(),
                            replacement: String::new(),
                            span: issue.span,
                        }),
                    ),
                };

                diagnostics.push(YamlValidationDiagnostic {
                    rule_id: rule_id.to_string(),
                    message: issue.message,
                    severity,
                    span: issue.span,
                    quick_fix,
                });
            }
        }

        // 2. Parse AST for structural checks
        let mut parser = YamlParser::new();
        match parser.parse(source) {
            Ok(ast) => {
                self.validate_ast(&ast, &mut diagnostics);
            }
            Err(YamlError::ParseError {
                message,
                line,
                column,
                offset,
            }) => {
                let pos = Position::new(line, column, offset);
                diagnostics.push(YamlValidationDiagnostic {
                    rule_id: "yaml-syntax-error".to_string(),
                    message,
                    severity: YamlSeverity::Error,
                    span: Span::new(pos, pos),
                    quick_fix: None,
                });
            }
            Err(e) => {
                let default_pos = Position::new(1, 1, 0);
                diagnostics.push(YamlValidationDiagnostic {
                    rule_id: "yaml-error".to_string(),
                    message: e.to_string(),
                    severity: YamlSeverity::Error,
                    span: Span::new(default_pos, default_pos),
                    quick_fix: None,
                });
            }
        }

        diagnostics
    }

    /// Validates an already constructed `YamlAST`.
    pub fn validate_ast(&self, ast: &YamlAST, diagnostics: &mut Vec<YamlValidationDiagnostic>) {
        // Check duplicate keys
        if self.options.check_duplicate_keys {
            let detector = DuplicateKeyDetector::new();
            let issues = detector.detect(ast);
            for issue in issues {
                diagnostics.push(YamlValidationDiagnostic {
                    rule_id: "yaml-duplicate-key".to_string(),
                    message: format!(
                        "Duplicate key '{}' (first defined on line {})",
                        issue.key, issue.original_line
                    ),
                    severity: YamlSeverity::Error,
                    span: issue.duplicate_span,
                    quick_fix: None,
                });
            }
        }

        // Check anchors and aliases
        if self.options.check_anchors_and_aliases {
            let extractor = AnchorExtractor::new();
            let anchors = extractor.extract(ast);

            let resolver = AliasResolver::new();
            let alias_issues = resolver.resolve(ast, &anchors);

            for issue in alias_issues {
                diagnostics.push(YamlValidationDiagnostic {
                    rule_id: match issue.kind {
                        crate::yaml::aliases::AliasIssueKind::UnresolvedAlias => {
                            "yaml-unresolved-alias"
                        }
                        crate::yaml::aliases::AliasIssueKind::CircularReference => {
                            "yaml-circular-alias"
                        }
                    }
                    .to_string(),
                    message: issue.message,
                    severity: YamlSeverity::Error,
                    span: issue.span,
                    quick_fix: None,
                });
            }
        }
    }
}
