name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-and-test:
    name: Build, Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Cargo Cache
        uses: Swatinem/rust-cache@v2

      - name: Check Formatting
        run: cargo fmt --check

      - name: Clippy Lints
        run: cargo clippy --workspace -- -D warnings

      - name: Run Unit Tests
        run: cargo test --workspace --all-targets
